### ISSUE TITLE
Bug in TcpConnection.cs, StartWaitingForChunk(StateObject state)?

### ISSUE THREAD

**Issue by PaulKemppi** [DarkRiftNetworking/Hazel-Networking#1]
Hi,
First of all, thank you for sharing the code GitHub. I noticed that large TCP packets (that arrive in several parts) are not received with the current version of the code. I fixed the problem by replacing line

socket.BeginReceive(state.buffer, state.totalBytesReceived, **state.buffer.Length**, SocketFlags.None, ChunkReadCallback, state);

with:

socket.BeginReceive(state.buffer, state.totalBytesReceived, **state.buffer.Length - state.totalBytesReceived**, SocketFlags.None, ChunkReadCallback, state);

Best Regards,
Paul

**Comment by JamJar00** [comment]
Thanks Paul, I've fixed this and pushed!
