### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by NimaAra** [DarkRiftNetworking/Hazel-Networking#2]
Hi,

Thank you for making this open source.

I understand the project is in beta but can you consider releasing a _PreRelease_ _NuGet_ package?

**Comment by JamJar00** [comment]
I'll look into it, I don't use NuGet much so I'm not sure how much work it'll take!

**Comment by NimaAra** [comment]
It's as simple as 1, 2, 3! Here are the [steps](http://docs.nuget.org/ndocs/create-packages/creating-a-package):
1. Generate Nuspec file; (one-time only)
2. Generate NuGet package;
3. Upload to NuGet.

You might want to do the above manually or as part of a build/release process if you have any.

**Comment by JamJar00** [comment]
Saw that link, I'll take a look over the weekend! 

The main problem would be keeping it in sync with GitHub, I like that I can push updates straight from VS to here and not need to worry about any other steps. Looks like it's possible to automate it though.

**Comment by NimaAra** [comment]
yes, it is possible. Take a look at some of my repositories.

The idea is at any point that you are happy with your source on GitHub, you create a _Release_ on GitHub, in doing so, you are capturing a snapshot of your code which you want to release, you then (as part of your automated build/release process) checkout the _Release_ version that you have created, build it, package it and push it to NuGet.

This whole thing can be done easily on [AppVeyor](https://www.appveyor.com/) (it's free for open source projects).

**Comment by JamJar00** [comment]
[Well we have a NuGet link now!](https://www.nuget.org/packages/DarkRiftNetworking.Hazel/)

It's not a pre-release one, I messed up the versions so it's marked itself as released!

**Comment by NimaAra** [comment]
Thank you for the quick turnaround.
