### ISSUE TITLE
broken link in Documentation/Readme.md

### ISSUE THREAD

**Issue by JoeStrout** [DarkRiftNetworking/Hazel-Networking#5]
The Readme file in that directory points to http://www.darkriftnetworking.com/docs, which is 404 Not Found.

**Comment by JoeStrout** [comment]
And actually, the same broken link is on this repo's top-level Readme file, too.

At this moment I have no idea where any documentation can actually be found.

**Comment by JamJar00** [comment]
Hey Joe, the website is currently down as my web hosts have changed something on the server and it's broken everything again... The documentation is auto-generated from the docs folder and xmldocs using Sandcastle so is still available in the project!

**Comment by JamJar00** [comment]
Should be fixed now!
