### ISSUE TITLE
Docs page 404

### ISSUE THREAD

**Issue by pajama** [DarkRiftNetworking/Hazel-Networking#6]
Referenced in the readme. Leads nowhere.
http://www.darkriftnetworking.com/docs

Cheers!

**Comment by JamJar00** [comment]
Apologies, I'll try and get it back up. It looks like it didn't move over to the new webserver with the rest!

**Comment by JamJar00** [comment]
It's now available [here](http://www.darkriftnetworking.com/Hazel/Docs). I'll try and update the repository links tomorrow for you 🙂

**Comment by JamJar00** [comment]
I've updated the readme 🙂
