### ISSUE TITLE
can add the client manager?

### ISSUE THREAD

**Issue by cnbryan** [DarkRiftNetworking/Hazel-Networking#8]
can add the client manager?
i think is necessary for game
just like   server.findclientbyid(guid)
and when client connected, the server and client need get the same id

**Comment by cnbryan** [comment]
and the webgl support

**Comment by JamJar00** [comment]
I feel this is very far outside of the scope of Hazel, Hazel is designed to be a low level networking layer and not have any high level functionality like that. If you require that then it would probably be something implemented in the application layer above Hazel.

WebGL is something I'd like to add but not high on my priority list. This should really be separate issue though, please ensure your issues are focused on **one** thing only and give **clear descriptions and use cases** for the functionality.

I'm marking this as invalid as it's not within scope of Hazel.
